### ISSUE TITLE
Android Basics: Lunch Tray app

### ISSUE THREAD

**Issue by gabbot1998** [google-developer-training/android-basics-kotlin-lunch-tray-app#22]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-project-lunch-tray?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-3-pathway-4%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-project-lunch-tray#2

**In which task and step of the codelab can this issue be found?**
Get started, where you set the text to listen for subtotal. 

**Describe the problem**
The `tools:text` doesn't match what should actually be the text value as the `tools:text` is missing a colon after subtotal. This is true in: the entree, side and accompaniment fragments but not in the checkout fragment. This led to confusion for me especially since the output of the failing test doesn't print the subtotal string that is wrong.

**Steps to reproduce?**
1. Go to fragment_entree_menu.xml
2. Lock at the `tools:text` field.
3. See that there is no colon after the subtotal.

**Comment by MadReza** [comment]
The tools namespace/library is just boilerplate. It helps display something when designing but it doesn't get compiled or executed.

So, they do not care and will not change it.

**Comment by osuleymanova** [comment]
@MadReza 
The issue that you presented to us is extremely important, and I thank you for bringing it to our attention. We did forget it, but since the functionality of the app doesn't change, and it's just placeholder text  that only appears in the preview, we're going to close the bug. But you can update the tools text in your version of the app.
